Feature/skale 779 full sync node
skalenetwork/skale-node pull request #428
Opened 2022-05-12 18:59 UTC by dmitry-tk

2022-05-17 15:43 UTC, badrogger requested changes

2022-05-17 15:43 UTC, badrogger commented on docker-compose-sync.yml
> +      test: ["CMD", "python3", "healthchecks/admin.py"]
Probably it won't work

2022-05-19 19:47 UTC, dmitry-tk commented on docker-compose-sync.yml
> +      test: ["CMD", "python3", "healthchecks/admin.py"]
this health check verifies that container prints something in logs at least once in 600 seconds, so it should still work with sync node

2022-05-20 09:25 UTC, badrogger approved these changes

2022-05-31 11:43 UTC, merged