Feature/skale 1801 new docker volume plugin
skalenetwork/skale-node pull request #45
Opened 2019-12-02 08:17 UTC by badrogger

2019-12-02 11:06 UTC, dmitry-tk commented on scripts/install.sh
> +docker_lvmpy_install
could we make this optional?
or mb let's create a script for the test launch?

2019-12-02 13:36 UTC, badrogger commented on scripts/install.sh
> +docker_lvmpy_install
I think it should be done in different patch

2019-12-02 17:35 UTC, dmytrotkk approved these changes

2019-12-19 09:18 UTC, kladkogex approved these changes

2019-12-27 11:09 UTC, dmytrotkk requested changes

2019-12-27 11:09 UTC, dmitry-tk commented on scripts/helper.sh
> +    git clone "https://$GITHUB_TOKEN@github.com/skalenetwork/docker-lvmpy.git" || true
let's remove `|| true` and add additional check here

2019-12-27 11:43 UTC, dmytrotkk approved these changes

2019-12-27 11:43 UTC, merged